version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
    open-pull-requests-limit: 5
    assignees:
      - "fanatixan"
    commit-message:
      prefix: "maven"
      include: "scope"
    labels:
      - "dependencies"
      - "maven"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:15"
    open-pull-requests-limit: 5
    assignees:
      - "fanatixan"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "ci"
